### ISSUE TITLE
Add Repository Topics to Enhance Visibility

### ISSUE THREAD

**Issue by tajmone** [rodrigorc/lemon_rust#7]
I've mentioned *Lemon Rust* in my new "Lemon Grove" project dedicated to Lemon:

- https://github.com/tajmone/lemon-grove#lemon-rust

I suggest you add the `lemon-parser-generator` and `lemon-parser` topics to Lemon Rust, so that the project can be more easily found by GitHub topics look-up:

- https://github.com/topics/lemon-parser-generator
- https://github.com/topics/lemon-parser

Unfortunately, right now both topics are practically empty, but hopefully in the future more Lemon related project will start to use topics.

Right now it's not easy to find Lemon projects by searching GitHub, because the `lemon` keyword yelds too many unrelated results (not to mention that there is language named [lemon](http://www.lemon-lang.org/)). The same is true for the [`lemon` topic ](https://github.com/topics/lemon), which is overcrowded too.

GitHub topics are a real blessing when it comes to finding relevant projects, and both `lemon-parser-generator` and `lemon-parser` are specific enough to grant no unrelated results.

**Comment by rodrigorc** [comment]
A "Lemon Grove"... that's interesting. I've added the suggested topics, thank you for your work.

I've been working recently in a re-implementation of this lemon-rust as a procedural macro. If successful, I will deprecate this one, and let you know, to update your list.
